### ISSUE TITLE
More variant interact protect

### ISSUE THREAD

**Issue by xMikux** [zetastormy/deluxe-hub#18]
### Describe the bug

I noticed there are some missing block interact, like all wood types of trapdoors (exclude oak wood), also the newer version of wood, can normally interect the door, fence gate, trapdoor, or more.

### Link to latest.log file

No error

### Steps to reproduce

1. Put any type of button, door, boat, chest with boat, trapdoor (ex cherry trapdoor)
2. Interact it!

### Expected behavior

All wood variant, like door, fence gate, sign, trapdoor, boat, chest with boat can get protect!

### Technical information

Server software: Paper
Server version: 1.21-109-master@5a5035b
Plugin version: Akropolis 1.5.3

**Comment by zetastormy** [comment]
Thank you for reporting, I will try to fix it before the next update!

**Comment by zetastormy** [comment]
I've tried to add as much blocks as possible. If there's any that's missing please create a new issue so I can look into that.
