### ISSUE TITLE
Adding a function to turn off the chat formatting not just removing the permissions

### ISSUE THREAD

**Issue by vaegq** [zetastormy/deluxe-hub#19]
### Is your feature request related to a problem?

I want to use lets say EssentialsXchat for chat formatting on my server and even when removing permissions for chat formatting from akropolis its still using the akropolis chat formatter as default and essentialsxchat is not working. And even if setting the permission to false would be working it's still a bit annoying to put the permission to disable chat formatting from akropolis to all the ranks on the server. Also if someone had everything set up on the server including chat formatting and just downloaded the plugin they would probably like me just fu** setting up the formatting for second time and just use the chat formatter they used before and from my experience it was not possible with essentialsxchat and setting the permission to false

### Describe the solution you'd like

just a simple chat-formatting: true/false above the chat formatting settings to enable or disable chat formatting

### Describe alternatives you've considered

no other alternatives that I considered

**Comment by vaegq** [comment]
my bad everything is actually good I thought was using EssentialsXChat and for 4 hours I was trying to fix it but realized that I was actually using LPC to manage my chat (my brain is off after 80h of not sleeping). Everything works fine now and after just removing all the configurations under chat management it works like it's turned off. But a function to just turn it off would be actually good

**Comment by zetastormy** [comment]
Thank you for your suggestion!
