### ISSUE TITLE
Add PlaceholderAPI Support

### ISSUE THREAD

**Issue by ProxTheSav** [zetastormy/deluxe-hub#22]
### Is your feature request related to a problem?

I am not able to list the players online perworld on the server selector

### Describe the solution you'd like

I would like to be able to add placeholders in the server selector

### Describe alternatives you've considered

ive tried to find a different hub plugin

**Comment by Fritx22** [comment]
PlaceholderAPI is completely supported and should work. As explained in the `config.yml` file, you need to use the format `<papi:placeholder>` to use PlaceholderAPI placeholders. For example, to show online players in the world `survival` you should use the placeholder `<papi:server_online_survival>`. This requires installing the [Server expansion for PlaceholderAPI](https://wiki.placeholderapi.com/users/placeholder-list/#server).

If it's still not working after trying this, send your configuration and server logs and we're happy to help.

**Comment by ProxTheSav** [comment]
Thank you!!!!!

Thanks,
Paul LaShomb
