### ISSUE TITLE
Could not pass event PlayerJoinEvent to Akroplis v1.6.0 (1.21.3/4)

### ISSUE THREAD

**Issue by GrimPlayzs** [zetastormy/deluxe-hub#23]
### Describe the bug

Error is logged when a player joins the server. This is due to specific actions that should be executed upon a player joining. 

### Link to latest.log file

https://mclo.gs/miN7yKv#L425

### Steps to reproduce

Update server jar to Paper 1.21.4
Install this plugin
Join the server
Witness the error in the log and no execution of commands.

### Expected behavior

For both the error to not happen and for the specific actions to be executed.

### Technical information

Paper
1.21.4 latest build
1.6.0

**Comment by zetastormy** [comment]
Fixed by b4427d30a631bcb62209a7703b27746b1033ce3d.
